### ISSUE TITLE
Using this with WinRM

### ISSUE THREAD

**Issue by lilasquared** [jmal98/ansiblecm#1]
Not really an issue, but I was wondering if you would be able to create a similar dockerfile where ansible is configured to connect to windows machines.  This is one article that explains it (also it is documented by ansible itself).

http://www.tomsitpro.com/articles/how-to-use-ansible-on-windows,1-3479.html

**Comment by jmal98** [comment]
I'm not familiar with using Ansible to manage Windows machines but I have reviewed the article and it looks like I just need to add the pywinrm dependency to the image and it should work.  I do not have a way to test the change to see if it works for your use case, but I will push the change and build a "latest" image tag.  Would you be able to test it and make sure it works for your use case?

**Comment by lilasquared** [comment]
I will give it a shot!

**Comment by jmal98** [comment]
Did it work for your use case?

**Comment by lilasquared** [comment]
Apologies for the delay - finally got some time to work on this.
I am getting this error when attempting to connect using kerbos
`FAILED! => {"msg": "The installed version of WinRM does not support transport(s) [u'kerbos']"}`

I wonder if these steps can be added to the docker file, and then the config file could be passed in?

**Comment by lilasquared** [comment]
additionally, when i try to build the image i get this error.
```
Step 1/10 : FROM alpine:3.7
 ---> 3fd9065eaf02
Step 2/10 : RUN apk add --no-cache 	bzip2=1.0.6-r6 	file=5.32-r0 	gzip=1.8-r0 	libffi=3.2.1-r4 	libffi-dev=3.2.1-r4 	musl-dev=1.1.18-r3 	openssl-dev=1.0.2n-r0 	python-dev=2.7.14-r2 	py-cffi=1.10.0-r0 	py-cryptography=2.0.3-r1 	py-pip=9.0.1-r1 	py-setuptools=33.1.1-r1 	py-yaml=3.12-r1 	tar=1.29-r1
 ---> Running in 41a5c13baa71
fetch http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.7/community/x86_64/APKINDEX.tar.gz
ERROR: unsatisfiable constraints:
  openssl-dev-1.0.2o-r0:
    breaks: world[openssl-dev=1.0.2n-r0]
The command '/bin/sh -c apk add --no-cache 	bzip2=1.0.6-r6 	file=5.32-r0 	gzip=1.8-r0 	libffi=3.2.1-r4 	libffi-dev=3.2.1-r4 	musl-dev=1.1.18-r3 	openssl-dev=1.0.2n-r0 	python-dev=2.7.14-r2 	py-cffi=1.10.0-r0 	py-cryptography=2.0.3-r1 	py-pip=9.0.1-r1 	py-setuptools=33.1.1-r1 	py-yaml=3.12-r1 	tar=1.29-r1' returned a non-zero code: 1
```

**Comment by lilasquared** [comment]
thanks! I will give it another shot!

**Comment by lilasquared** [comment]
@jmal98 this worked successfully for me - thank you so much!

**Comment by lilasquared** [comment]
I will as soon as I can.  As for the playbook It is using the windows modules to connect to a remove windows server 2016 to perform the tasks.  Does that answer your question?

**Comment by lilasquared** [comment]
@jmal98 using the build of the latest image my playbook is working and managing my windows nodes! You should publish this to the docker registry!

**Comment by jmal98** [comment]
Great, glad it fixed it.

The update image has been pushed to Docker hub.
