### ISSUE TITLE
How to use it without running playbooks directly

### ISSUE THREAD

**Issue by ricardogaspar2** [jmal98/ansiblecm#4]
Hi, I was looking for a docker image with all the needed software to run an ansible CM and I found yours. But I noticed that I couldn't log in to the container directly (via bash: `$ docker run -it jmal98/ansiblecm bash`) only execute commands/playbooks directly. 

Is there a way to access the container via bash and do whatever I need (like changing the inventory, install modules, add playbooks, etc.) ?

Thanks in advance.

**Comment by lilasquared** [comment]
nevermind the answer is yes :+1:
