### ISSUE TITLE
Error: unsatisfiable constraints

### ISSUE THREAD

**Issue by NasAmin** [jmal98/ansiblecm#5]
Hi,

I am trying to build the docker image locally and I am getting the following error:

> apk del build-dependencies
 ---> Running in 6ffeab2d70a3
fetch http://dl-cdn.alpinelinux.org/alpine/v3.8/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.8/community/x86_64/APKINDEX.tar.gz
ERROR: unsatisfiable constraints:
  krb5-libs-1.15.3-r0:
    breaks: world[krb5-libs=1.15.2-r2]
    satisfies:
               krb5-dev-1.15.3-r0[krb5-libs=1.15.3-r0]
               krb5-1.15.3-r0[so:libgssapi_krb5.so.2]
               krb5-1.15.3-r0[so:libk5crypto.so.3]
               krb5-1.15.3-r0[so:libkadm5clnt_mit.so.11]
               krb5-1.15.3-r0[so:libkadm5srv_mit.so.11]
               krb5-1.15.3-r0[so:libkdb5.so.8]
               krb5-1.15.3-r0[so:libkrb5.so.3]
               krb5-1.15.3-r0[so:libkrb5support.so.0]
               krb5-server-ldap-1.15.3-r0[so:libgssrpc.so.4]
               krb5-server-ldap-1.15.3-r0[so:libkadm5srv_mit.so.11]
               krb5-server-ldap-1.15.3-r0[so:libkdb5.so.8]
               krb5-server-ldap-1.15.3-r0[so:libkrb5.so.3]
               krb5-server-ldap-1.15.3-r0[so:libkrb5support.so.0]

I am not very familiar with constraints. Can you please provide some guidance.
I am using docker for windows 10 in linux mode.

I ran the following command to build the docker image

`docker build --tag anciblecm:2.6.2 .`

**Comment by jmal98** [comment]
The Dockerfile pins the versions of certain packages based on what is available at the time.  A list of available packages can be found at https://pkgs.alpinelinux.org/packages.

As time goes on, packages are upgraded and older versions are marked as breaking so either you can update the package to use a newer version, or remove the version specifier all together.

**Comment by NasAmin** [comment]
Thanks a lot.
